### ISSUE TITLE
模型问题

### ISSUE THREAD

**Issue by liuchenxin666** [mikugyf/PMIQD-SIS#1]
我注意到在pmiqd.py中，PMIQA类仅仅是一些卷积，没有用到该文件下其他类。而在main.py中却使用PMIQA作为模型训练测试，这与论文也是不一致的。想问是否有更完善的代码呢？希望得到作者解答，万分感谢。

**Comment by mikugyf** [comment]
函数中模型是通过调用子模块来实现的，因子模块中包含其他作者内容，所以没有直接写在这里而是放了链接代码，再通过调用来实现（需要自行调整）。因后续任务要求问题还没有更完善的代码，具体可以通过论文内容进行调整和复现。
数据集目前是完全公开以及提供使用的，欢迎使用以及研究。
感谢您的提问，希望可以帮助到您！

**Comment by liuchenxin666** [comment]
感谢您的回复~
不过saliency文件夹下readme中，引用的链接应该有误吧。DINet应该是https://github.com/ysyscool/DINet

**Comment by mikugyf** [comment]
感谢指正！
